"""add journals table

Revision ID: 6f94f5cae8c1
Revises: d3f6136ee6f1
Create Date: 2026-07-10 00:05:06.681175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f94f5cae8c1'
down_revision: Union[str, None] = 'd3f6136ee6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('date_label', sa.String(length=50), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('article_intros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_articles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('music_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('music_tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('photo_narrative', sa.Text(), nullable=True),
    sa.Column('prompt_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_date', name='uq_journal_user_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journals')
    # ### end Alembic commands ###
