"""add content_hash to photos for dedup

Revision ID: d3f6136ee6f1
Revises: 4c6d6d9da1ba
Create Date: 2026-07-08 15:11:48.490948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f6136ee6f1'
down_revision: Union[str, None] = '4c6d6d9da1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index('idx_photo_user_hash', 'photos', ['user_id', 'content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_photo_user_hash', table_name='photos')
    op.drop_column('photos', 'content_hash')
    # ### end Alembic commands ###
